version: "3.8"

services:
  db:
    image: postgres:13.3-alpine
    container_name: "database"
    ports:
      - "5000:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - fullstack
    volumes:
      - database_postgres_go:/var/lib/postgres/data
  web:
    build: ./
    container_name: "go-socket-app"
    environment:
      DB_USERNAME: "postgres"
      DB_PASSWORD: "postgres"
      DB_DB: "postgres"
      DB_SCHEMA: "public"
      DB_PORT: "5432"
    ports:
      - "8000:8080"
    depends_on:
      - db
    networks:
      - fullstack
volumes:
  database_postgres_go:
    name: "volumes_database_postgres_go"
networks:
  fullstack:
    driver: bridge
    name: "networks_bridge_fullstack"
